stages:
  - pages
create-pages:
  stage: pages
  image: oven/bun:latest
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: screentimer/dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == "react-prototype"
  before_script:
    # Install dependencies based on lock files
    - bun install --frozen-lockfile
  script:
    # Build app
    - bunx vite build
  cache:
    paths:
      - screentimer/node_modules
    key:
      files:
        - bun.lock
